---
- hosts: "all"
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
    - name: delete file
      ignore_errors: yes
      file:
        state: absent
        path: /etc/containerd/config.toml

    - name: Copy config containerd
      copy:
        src: "./files/config.toml"
        dest: /etc/containerd/config.toml
        remote_src: no
        mode: 0644
        owner: root
        group: root

    # - name: Ansible create file if it doesn't exist example
    #   ignore_errors: yes
    #   file:
    #     path: "/etc/containerd/config.toml"
    #     state: touch
    #     mode: 0666

    # - name: делаем дефалтным конфиг containerd
    #   command: "sudo containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1"
    #   become: true

    # - name: делаем дефалтным конфиг containerd
    #   command: "sudo containerd config default > /etc/containerd/config.toml"
    # #  become: true

    # - name: configure the systemd cgroup driver for runC
    #   command: "sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml"
    #   become: true

    # - name: configure the systemd cgroup driver for runC
    #   lineinfile:
    #     path: /etc/containerd/config.toml
    #     regexp: "^(.*)SystemdCgroup(.*)$"
    #     line: "SystemdCgroup = true"
